name: Build SMBIOS Generator GUI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform:
          - windows-latest
          - macos-latest
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pyinstaller requests

      - name: Build executable on Windows
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          pyinstaller --onefile main.py --name main.exe
          Compress-Archive -Path dist\main.exe -DestinationPath SMBIOS-GUI-Windows.zip

      - name: Build executable on macOS
        if: runner.os == 'macOS'
        shell: bash
        run: |
          pyinstaller --onefile main.py --name main
          zip -r SMBIOS-GUI-macOS.zip dist/main

      - name: Build executable on Ubuntu
        if: runner.os == 'Linux'
        shell: bash
        run: |
          pyinstaller --onefile main.py --name main
          zip -r SMBIOS-GUI-Linux.zip dist/main

      - name: Upload artifact on Windows
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: SMBIOS-GUI-Windows
          path: SMBIOS-GUI-Windows.zip

      - name: Upload artifact on macOS
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: SMBIOS-GUI-macOS
          path: SMBIOS-GUI-macOS.zip

      - name: Upload artifact on Ubuntu
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: SMBIOS-GUI-Linux
          path: SMBIOS-GUI-Linux.zip
