name: Build SMBIOS Generator GUI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform:
          - windows-latest
          - macos-latest
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pyinstaller requests

      - name: Build executable with PyInstaller
        run: |
          if [[ "${{ matrix.platform }}" == "windows-latest" ]]; then
            pyinstaller --onefile main.py --name main.exe
            zip -r SMBIOS-GUI-Windows.zip dist/main.exe
          elif [[ "${{ matrix.platform }}" == "macos-latest" ]]; then
            pyinstaller --onefile main.py --name main
            zip -r SMBIOS-GUI-macOS.zip dist/main
          else
            pyinstaller --onefile main.py --name main
            zip -r SMBIOS-GUI-Linux.zip dist/main
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SMBIOS-GUI-${{ matrix.platform == 'windows-latest' && 'Windows' || matrix.platform == 'macos-latest' && 'macOS' || 'Linux' }}
          path: |
            SMBIOS-GUI-Windows.zip
            SMBIOS-GUI-macOS.zip
            SMBIOS-GUI-Linux.zip
