name: Build SMBIOS Generator GUI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pyinstaller requests

      - name: Build executable
        run: pyinstaller --noconfirm --onefile --windowed main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: SMBIOS-GUI-Windows
          path: dist/main.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pyinstaller requests

      - name: Build executable
        run: pyinstaller --noconfirm --onefile --windowed main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: SMBIOS-GUI-macOS
          path: dist/main

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pyinstaller requests

      - name: Build executable
        run: pyinstaller --noconfirm --onefile --windowed main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: SMBIOS-GUI-Linux
          path: dist/main
